### PR TITLE
onPrev, onNext and onDone event callbacks to element options

### PR DESCRIPTION
**Pull request by Yahasana**
Add `onPrev`, `onNext` and `onDone` callbacks options to element's options.  `onStart` features can be implemented by test `options.isFirst` in the callbacks.

image

fixed issues #51 and #69

### CODE REVIEW

**Comment by kamranahmedse** [comment]
Thanks for the PR. It has been added in 0.6

**Comment by TiagoSilvaPereira** [comment]
Are these modifications on CDN version?

**Comment by anhnguyen72** [comment]
> Thanks for the PR. It has been added in 0.6

I'm using v0.9 but does not existed onDone, onClose

**Comment by maczyt** [comment]
@anhnguyen72 you can use `onReset`

**Comment by kevinoehme** [comment]
Hi @kamranahmedse When will the onClose() or onDone() Function be available in the master? Would be extremely helpful! Best regards!

**Comment by koutsenko** [comment]
How can I distinguish last step was successfuly done by "Done" button or closed by "Close" button? 

onNext will not work for "Done" button.
onReset event triggers for both events.

@kamranahmedse hello, why that PR was closed? :(

**Comment by Yahasana** [comment]
hi folks, stop to issue on this topic again. my implement in this pull is too smart to be merged. bye

**Comment by renyangmei** [comment]
> Thanks for the PR. It has been added in 0.6

I'm using v0.9.8  but does not existed onDone, onClose  (⊙︿⊙)

**Pull request closed without merging**
