### PR TITLE
allow to show stage background in no-animate mode

### PR DESCRIPTION
**Pull request by Yahasana**

### CODE REVIEW

**Comment by kamranahmedse** [comment]
Hey, that is on purpose.

**Comment by Yahasana** [comment]
this will suspend `stageBackground` option 👎

**Comment by kamranahmedse** [comment]
Hey, the animated version is different from the non-animated version. There might be stacking context issues that are not handled by the animated version, so non-animated also acts as a fallback and solves those issues. The reason why we don't have the background for the stage is:

We don't have the dark overlay for the page in the non-animated version, it is achieved by the stage with the transparent background and having a high outline value in the non-animated version. The stage is placed above/below (depending upon the computed z-index value) and if it has the background, the element below it will get invisible, so to make the "highlighted" element below it visible it has the transparent background. 

Look at the image below from the issue https://github.com/kamranahmedse/driver.js/issues/60 for the reason

image

**Comment by Yahasana** [comment]
I know this issue and I think it's good to add a stage highlight background to the active element, which help user to know which elements he should focus. 

See my case below, the green box is the stage background.
image

**Comment by Yahasana** [comment]
All rights, may `background:transparent!important` be required for that fix. It doesn't work in my case. so I fix it in other way. ignore me

**Pull request closed without merging**
